### ISSUE TITLE
No permissions to /dev/dri

### ISSUE THREAD

**Issue by cizra** [Nicceboy/gamify-containers#3]
On host machine, I'm in the `video` group, which gives me permissions to render.
Inside the Docker container, though, numeric UIDs are mapped differently, so I don't have these permissions.

Suggest adding `usermod -a -G $(stat -c %g /dev/dri/card0) lutris` to entrypoint.sh.

**Comment by Nicceboy** [comment]
Good suggestion. 
For future note, in case different cards exists and they have different permissions, manual intervention is required. I don't know if there are any good dynamic solution for that. Maybe loop all cards? Might be rare case anyway.
